#!/usr/bin/env sh

# default options
MYSQL_HOST=localhost
MYSQL_USER=root
MYSQL_PASS=
PASSWORD_LENGTH=20

usage() {
    echo "Usage: $(basename $0) OPTIONS CMD"
    echo
    echo "OPTIONS: -H, -u, -p, -n, -d, -v, -m, -r, -b, -z"
    echo "    -H: MySQL host"
    echo "    -u: MySQL username"
    echo "    -p: MySQL password"
    echo "    -n: Dry run. Don't execute any SQL command."
    echo "    -d: Debug mode"
    echo "    -v: Verbose output"
    echo "    -m: Create database with same name as user"
    echo "    -r: Delete both user and database"
    echo "    -b: Set backup directory"
    echo "    -z: Compress backup"
    echo
    echo "COMMANDS: create|delete|backup|dump|grant|ls"
    echo "    create [db|user] ITEM"
    echo "        Create user or database"
    echo "        -m: Create a new database with the same name as the new user"
    echo "    delete [db|user] ITEM"
    echo "        Delete user or database"
    echo "        -r: Remove both user and database"
    echo "    backup DATABASE [TABLE]"
    echo "        Backup database or specific table"
    echo "        -z: Compress backup (gzip)"
    echo "        -b DIR: Set backup directory (default is PWD)"
    echo "    dump DATABASE [TABLE]"
    echo "        Dump whole database or specific table(s)"
    echo "    grant DATABASE USER PASSWORD"
    echo "        Grant access to database to user"
    echo "    ls [db|user|grant]"
    echo "        List databases, users, permissions"
    [[ -n $1 ]] && exit $1
}

generate_password() {
     tr -dc '[:alnum:]' < /dev/urandom | fold -w "$1" | head -1
}

create_user() {
    [[ "$VERBOSE" -eq 1 ]] && echo "Create user $1"
    local query="CREATE USER '$1'@'$MYSQL_HOST' IDENTIFIED BY '$2';"
    $MYSQL_CMD "$query"
}

create_db() {
    [[ "$VERBOSE" -eq 1 ]] && echo "Create database $1"
    local query="CREATE DATABASE IF NOT EXISTS $1;"
    $MYSQL_CMD "$query"
}

grant() {
    [[ "$VERBOSE" -eq 1 ]] && echo "Grant all on $1 to $2"
    local query="\
        GRANT ALL ON ${1}.* TO '$2'@'$MYSQL_HOST' IDENTIFIED BY '$3'; \
        FLUSH PRIVILEGES;"
    $MYSQL_CMD "$query"
}

delete_user() {
    # MySQL < 5.0.2
    # local query="DROP USER '$1'@'$MYSQL_HOST';"
    # MySQL > 5.0.2
    # local query="DROP USER '$1';"
    local query="DROP USER '$1'@'$MYSQL_HOST';"
    $MYSQL_CMD "$query"
}

delete_db() {
    local query="DROP DATABASE $1;"
    $MYSQL_CMD "$query"
}

ls_db() {
    local query="show databases;"
    $MYSQL_CMD "$query"
}

ls_users() {
    local query="SELECT User FROM mysql.user;"
    $MYSQL_CMD "$query"
}

ls_grants() {
    local query="SHOW GRANTS FOR '$1'@'$MYSQL_HOST';"
    $MYSQL_CMD "$query"
}

dump() {
    $MYSQL_DUMP_CMD "$@"
}

backup() {
    [[ -z "$BACKUP_DIR" ]] && BACKUP_DIR=$(pwd)
    # Remove trailing '/'
    BACKUP_DIR=$(sed 's|/\+$||' <<< "$BACKUP_DIR")
    local mysql_db="$1"
    local mysql_table="$2"
    local backup_file="${BACKUP_DIR}/${mysql_db}"
    [[ -n "$mysql_table" ]] && backup_file="${backup_file}.${mysql_table}"
    backup_file="${backup_file}_$(date '+%d%m%Y_%H%M%S').log"
    [[ "$COMPRESSION" -eq 1 ]] && backup_file="${backup_file}.gz"
    local save_file="> $backup_file"
    [[ "$COMPRESSION" -eq 1 ]] && save_file="| gzip -c > $backup_file"
    eval "$MYSQL_DUMP_CMD --lock-tables=false $mysql_db $mysql_table $save_file"
}

recap_db_create() {
    echo "Successfully created database '$1'"
}

recap_db_delete() {
    echo "Successfully removed database '$1'"
}

recap_user_create() {
    echo "Successfully created user '$1' with password '$2'"
}

recap_user_delete() {
    echo "Successfully removed user '$1'"
}

recap_grant() {
    echo "Successfully granted access to database '$1' to user '$2'"
}

OPTS=`getopt -o b:dhH:l:mnp:ru:vz --long backup-dir:,debug,help,host:,password-length:,dryrun,create-db,password:,recursive,username:,verbose,compress -n '$(basename $0)' -- "$@"`
eval set -- "$OPTS"

while :
do
    case "$1" in
        -d|--debug)
            DEBUG=1
            shift
            ;;
        -v|--verbose)
            VERBOSE=1
            shift
            ;;
        -n|--dryrun)
            DRYRUN=1
            shift
            ;;
        -h|--help)
            usage 0
            ;;
        -H|--host)
            MYSQL_HOST="$2"
            shift 2
            ;;
        -u|--username)
            MYSQL_USER="$2"
            shift 2
            ;;
        -p|--password)
            MYSQL_PASS="$2"
            shift 2
            ;;
        -r|--recursive)
            RECURSIVE=1
            shift
            ;;
        -m|--create-db)
            CREATE_DB=1
            shift
            ;;
        -p|--password-length)
            PASSWORD_LENGTH="$2"
            shift 2
            ;;
        -b|--backup-dir)
            BACKUP_DIR="$2"
            shift 2
            ;;
        -z|--compress)
            COMPRESSION=1
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            echo "Internal error!"
            exit 1
            ;;
    esac
done

MYSQL_CMD="mysql -h $MYSQL_HOST -u${MYSQL_USER} -p${MYSQL_PASS} -e"
MYSQL_DUMP_CMD="mysqldump -h $MYSQL_HOST -u${MYSQL_USER} -p${MYSQL_PASS}"

[[ "$DRYRUN" -eq 1 ]] && {
    MYSQL_CMD="echo $MYSQL_CMD"
    MYSQL_DUMP_CMD="echo $MYSQL_DUMP_CMD"
}

case "$1" in
    h|help)
        usage 0
        ;;
    c|create|n|new)
        case "$2" in
            u|user)
                mysql_user="$3"
                mysql_pass="$4"
                [[ -n "$mysql_user" ]] || usage 2
                [[ -z "$mysql_pass" ]] && {
                    mysql_pass=$(generate_password $PASSWORD_LENGTH)
                }
                create_user "$mysql_user" "$mysql_pass" && {
                    recap_user_create "$mysql_user" "$mysql_pass"
                }
                [[ "$CREATE_DB" -eq 1 ]] && {
                    create_db "$mysql_user" && {
                        recap_db_create "$mysql_db"
                        grant "$mysql_user" "$mysql_user" "$mysql_pass" && {
                            recap_grant "$mysql_db"
                        }
                    }
                }
                ;;
            d|db|database)
                # TODO
                mysql_db="$3"
                [[ -n "$mysql_db" ]] || usage 2
                create_db "$mysql_db" && {
                    recap_db_create "$mysql_db"
                }
                ;;
            *)
                usage 2
                ;;
        esac
        ;;
    d|delete|rm|remove)
        case "$2" in
            u|user)
                mysql_user="$3"
                mysql_db="$mysql_user"
                [[ -n "$mysql_user" ]] || usage 2
                delete_user "$mysql_user" && {
                    recap_user_delete "$mysql_user"
                }
                user_delete_success=$?
                # Delete database having the same name as user
                [[ "$RECURSIVE" -eq 1 ]] && {
                    delete_db "$mysql_db" && {
                        recap_db_delete "$mysql_db"
                    }
                }
                ;;
            d|db|database)
                mysql_db=$3
                [[ -n "$mysql_db" ]] || usage 2
                delete_db "$mysql_db" && recap_db_delete "$mysql_db"
                ;;
        esac
        ;;
    b|backup)
        mysql_db="$2"
        mysql_table="$3"
        [[ -n "$mysql_db" ]] || usage 2
        backup "$mysql_db" "$mysql_table"
        ;;
    dump)
        [[ -n "$2" ]] || usage 2
        shift
        dump "$@"
        ;;
    g|grant)
        mysql_db="$2"
        mysql_user="$3"
        mysql_pass="$4"
        grant "$mysql_user" "$mysql_user" "$mysql_pass" && {
            recap_grant "$mysql_user" "$mysql_user" "$mysql_pass"
        }
        ;;
    l|ls|list)
        case "$2" in
            u|user|users)
                ls_users
                ;;
            d|db|database)
                ls_db
                ;;
            g|grants)
                ls_grants "$3"
                ;;
            '')
                ls_db
                ls_users
                ;;
            *)
                usage 2
                ;;
        esac
        ;;
    *)
        usage 2
        ;;
esac

RESULT=$?

[[ "$DEBUG" -eq 1 ]] && {
    echo "OPTS: $OPTS"
    echo "Verbose: $VERBOSE"
    echo "Dryrun: $DRYRUN"
    echo "MySQL host: $MYSQL_HOST"
    echo "MySQL user: $MYSQL_USER"
    echo "MySQL pass: $MYSQL_PASS"
    echo "MySQL cmd: $MYSQL_CMD"
    echo "Create DB: $CREATE_DB"
    echo "Remaining arguments:"
    for arg do echo '--> '"\`$arg'" ; done
}

[[ "$RESULT" -eq 0 ]]
